import {
  Accordion,
  AccordionDetails,
  AccordionSummary,
  Box,
  Divider,
  Typography,
} from "@mui/material";
import { Connection, useTimetableContext } from "./TimetableSearchProvider";
import ExpandMoreIcon from "@mui/icons-material/ExpandMore";
import { format } from "date-fns";
import { TimetableResult } from "./TimetableResult";

export const TimetableResults = () => {
  //   const { connections } = useTimetableContext();
  //   console.log(connections);

  //   // const connections = {

  //   // }
  return (
    <>
      {connections.map((connection, index) => {
        return <TimetableResult key={index} connection={connection} />;
      })}
    </>
  );
};

const connections = [
  {
    from: {
      station: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
      arrival: null,
      arrivalTimestamp: null,
      departure: "2022-05-01T17:28:00+0200",
      departureTimestamp: 1651418880,
      delay: null,
      platform: "5",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
    },
    to: {
      station: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
      arrival: "2022-05-01T20:18:00+0200",
      arrivalTimestamp: 1651429080,
      departure: null,
      departureTimestamp: null,
      delay: null,
      platform: "3",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
    },
    duration: "00d02:50:00",
    transfers: 1,
    service: null,
    products: ["EC", "IC 1"],
    capacity1st: null,
    capacity2nd: null,
    sections: [
      {
        journey: {
          name: "010059",
          category: "EC",
          subcategory: null,
          categoryCode: null,
          number: "010059",
          operator: "SBB",
          to: "Domodossola (I)",
          passList: [
            {
              station: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
              arrival: null,
              arrivalTimestamp: null,
              departure: "2022-05-01T17:28:00+0200",
              departureTimestamp: 1651418880,
              delay: null,
              platform: "5",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500218",
                name: "Olten",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.351936,
                  y: 7.907707,
                },
                distance: null,
              },
              arrival: "2022-05-01T17:55:00+0200",
              arrivalTimestamp: 1651420500,
              departure: "2022-05-01T17:58:00+0200",
              departureTimestamp: 1651420680,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500218",
                name: "Olten",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.351936,
                  y: 7.907707,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "0000132",
                name: "Bahn-2000-Strecke",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.196371,
                  y: 7.689367,
                },
                distance: null,
              },
              arrival: null,
              arrivalTimestamp: null,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "0000132",
                name: "Bahn-2000-Strecke",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.196371,
                  y: 7.689367,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:26:00+0200",
              arrivalTimestamp: 1651422360,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "4",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
          arrival: null,
          arrivalTimestamp: null,
          departure: "2022-05-01T17:28:00+0200",
          departureTimestamp: 1651418880,
          delay: null,
          platform: "5",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
          arrival: "2022-05-01T18:26:00+0200",
          arrivalTimestamp: 1651422360,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "4",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
        },
      },
      {
        journey: {
          name: "000728",
          category: "IC",
          subcategory: null,
          categoryCode: null,
          number: "1",
          operator: "SBB",
          to: "Genève-Aéroport",
          passList: [
            {
              station: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:26:00+0200",
              arrivalTimestamp: 1651422360,
              departure: "2022-05-01T18:34:00+0200",
              departureTimestamp: 1651422840,
              delay: null,
              platform: "5",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504100",
                name: "Fribourg/Freiburg",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.803151,
                  y: 7.151052,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:55:00+0200",
              arrivalTimestamp: 1651424100,
              departure: "2022-05-01T18:56:00+0200",
              departureTimestamp: 1651424160,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504100",
                name: "Fribourg/Freiburg",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.803151,
                  y: 7.151052,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501120",
                name: "Lausanne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.516795,
                  y: 6.629087,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:40:00+0200",
              arrivalTimestamp: 1651426800,
              departure: "2022-05-01T19:43:00+0200",
              departureTimestamp: 1651426980,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501120",
                name: "Lausanne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.516795,
                  y: 6.629087,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:18:00+0200",
              arrivalTimestamp: 1651429080,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "3",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
          arrival: "2022-05-01T18:26:00+0200",
          arrivalTimestamp: 1651422360,
          departure: "2022-05-01T18:34:00+0200",
          departureTimestamp: 1651422840,
          delay: null,
          platform: "5",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
          arrival: "2022-05-01T20:18:00+0200",
          arrivalTimestamp: 1651429080,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "3",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
        },
      },
    ],
  },
  {
    from: {
      station: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
      arrival: null,
      arrivalTimestamp: null,
      departure: "2022-05-01T18:03:00+0200",
      departureTimestamp: 1651420980,
      delay: null,
      platform: "14",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
    },
    to: {
      station: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
      arrival: "2022-05-01T20:47:00+0200",
      arrivalTimestamp: 1651430820,
      departure: null,
      departureTimestamp: null,
      delay: null,
      platform: "4",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
    },
    duration: "00d02:44:00",
    transfers: 1,
    service: null,
    products: ["IC 51", "IC 5"],
    capacity1st: null,
    capacity2nd: null,
    sections: [
      {
        journey: {
          name: "001632",
          category: "IC",
          subcategory: null,
          categoryCode: null,
          number: "51",
          operator: "SBB",
          to: "Biel/Bienne",
          passList: [
            {
              station: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
              arrival: null,
              arrivalTimestamp: null,
              departure: "2022-05-01T18:03:00+0200",
              departureTimestamp: 1651420980,
              delay: null,
              platform: "14",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500113",
                name: "Laufen",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.419347,
                  y: 7.502642,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:20:00+0200",
              arrivalTimestamp: 1651422000,
              departure: "2022-05-01T18:21:00+0200",
              departureTimestamp: 1651422060,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500113",
                name: "Laufen",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.419347,
                  y: 7.502642,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500109",
                name: "Delémont",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.36201,
                  y: 7.35008,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:37:00+0200",
              arrivalTimestamp: 1651423020,
              departure: "2022-05-01T18:42:00+0200",
              departureTimestamp: 1651423320,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500109",
                name: "Delémont",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.36201,
                  y: 7.35008,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500105",
                name: "Moutier",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.280676,
                  y: 7.38105,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:51:00+0200",
              arrivalTimestamp: 1651423860,
              departure: "2022-05-01T18:52:00+0200",
              departureTimestamp: 1651423920,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500105",
                name: "Moutier",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.280676,
                  y: 7.38105,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500159",
                name: "Grenchen Nord",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.191696,
                  y: 7.38963,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:00:00+0200",
              arrivalTimestamp: 1651424400,
              departure: "2022-05-01T19:01:00+0200",
              departureTimestamp: 1651424460,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500159",
                name: "Grenchen Nord",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.191696,
                  y: 7.38963,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:10:00+0200",
              arrivalTimestamp: 1651425000,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "4",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
          arrival: null,
          arrivalTimestamp: null,
          departure: "2022-05-01T18:03:00+0200",
          departureTimestamp: 1651420980,
          delay: null,
          platform: "14",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
          arrival: "2022-05-01T19:10:00+0200",
          arrivalTimestamp: 1651425000,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "4",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
        },
      },
      {
        journey: {
          name: "000532",
          category: "IC",
          subcategory: null,
          categoryCode: null,
          number: "5",
          operator: "SBB",
          to: "Genève-Aéroport",
          passList: [
            {
              station: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:10:00+0200",
              arrivalTimestamp: 1651425000,
              departure: "2022-05-01T19:16:00+0200",
              departureTimestamp: 1651425360,
              delay: null,
              platform: "5",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504221",
                name: "Neuchâtel",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.996727,
                  y: 6.935713,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:32:00+0200",
              arrivalTimestamp: 1651426320,
              departure: "2022-05-01T19:34:00+0200",
              departureTimestamp: 1651426440,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504221",
                name: "Neuchâtel",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.996727,
                  y: 6.935713,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504200",
                name: "Yverdon-les-Bains",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.78155,
                  y: 6.640943,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:52:00+0200",
              arrivalTimestamp: 1651427520,
              departure: "2022-05-01T19:54:00+0200",
              departureTimestamp: 1651427640,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504200",
                name: "Yverdon-les-Bains",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.78155,
                  y: 6.640943,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501037",
                name: "Morges",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.511111,
                  y: 6.493971,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:16:00+0200",
              arrivalTimestamp: 1651428960,
              departure: "2022-05-01T20:18:00+0200",
              departureTimestamp: 1651429080,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501037",
                name: "Morges",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.511111,
                  y: 6.493971,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:47:00+0200",
              arrivalTimestamp: 1651430820,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "4",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
          arrival: "2022-05-01T19:10:00+0200",
          arrivalTimestamp: 1651425000,
          departure: "2022-05-01T19:16:00+0200",
          departureTimestamp: 1651425360,
          delay: null,
          platform: "5",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
          arrival: "2022-05-01T20:47:00+0200",
          arrivalTimestamp: 1651430820,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "4",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
        },
      },
    ],
  },
  {
    from: {
      station: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
      arrival: null,
      arrivalTimestamp: null,
      departure: "2022-05-01T18:16:00+0200",
      departureTimestamp: 1651421760,
      delay: null,
      platform: "12",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
    },
    to: {
      station: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
      arrival: "2022-05-01T21:18:00+0200",
      arrivalTimestamp: 1651432680,
      departure: null,
      departureTimestamp: null,
      delay: null,
      platform: "3",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
    },
    duration: "00d03:02:00",
    transfers: 2,
    service: null,
    products: ["IR 27", "IR 16", "IC 1"],
    capacity1st: null,
    capacity2nd: null,
    sections: [
      {
        journey: {
          name: "002483",
          category: "IR",
          subcategory: null,
          categoryCode: null,
          number: "27",
          operator: "SBB",
          to: "Luzern",
          passList: [
            {
              station: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
              arrival: null,
              arrivalTimestamp: null,
              departure: "2022-05-01T18:16:00+0200",
              departureTimestamp: 1651421760,
              delay: null,
              platform: "12",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500023",
                name: "Liestal",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.484462,
                  y: 7.731377,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:26:00+0200",
              arrivalTimestamp: 1651422360,
              departure: "2022-05-01T18:27:00+0200",
              departureTimestamp: 1651422420,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500023",
                name: "Liestal",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.484462,
                  y: 7.731377,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500026",
                name: "Sissach",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.462752,
                  y: 7.812039,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:32:00+0200",
              arrivalTimestamp: 1651422720,
              departure: "2022-05-01T18:33:00+0200",
              departureTimestamp: 1651422780,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500026",
                name: "Sissach",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.462752,
                  y: 7.812039,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500027",
                name: "Gelterkinden",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.465888,
                  y: 7.847673,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:36:00+0200",
              arrivalTimestamp: 1651422960,
              departure: "2022-05-01T18:37:00+0200",
              departureTimestamp: 1651423020,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500027",
                name: "Gelterkinden",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.465888,
                  y: 7.847673,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500218",
                name: "Olten",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.351936,
                  y: 7.907707,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:48:00+0200",
              arrivalTimestamp: 1651423680,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "12",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500218",
                name: "Olten",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.351936,
                  y: 7.907707,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
          arrival: null,
          arrivalTimestamp: null,
          departure: "2022-05-01T18:16:00+0200",
          departureTimestamp: 1651421760,
          delay: null,
          platform: "12",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8500218",
            name: "Olten",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.351936,
              y: 7.907707,
            },
            distance: null,
          },
          arrival: "2022-05-01T18:48:00+0200",
          arrivalTimestamp: 1651423680,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "12",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8500218",
            name: "Olten",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.351936,
              y: 7.907707,
            },
            distance: null,
          },
        },
      },
      {
        journey: {
          name: "003182",
          category: "IR",
          subcategory: null,
          categoryCode: null,
          number: "16",
          operator: "SBB",
          to: "Bern",
          passList: [
            {
              station: {
                id: "8500218",
                name: "Olten",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.351936,
                  y: 7.907707,
                },
                distance: null,
              },
              arrival: "2022-05-01T18:48:00+0200",
              arrivalTimestamp: 1651423680,
              departure: "2022-05-01T18:58:00+0200",
              departureTimestamp: 1651424280,
              delay: null,
              platform: "8",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500218",
                name: "Olten",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.351936,
                  y: 7.907707,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "0000132",
                name: "Bahn-2000-Strecke",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.196371,
                  y: 7.689367,
                },
                distance: null,
              },
              arrival: null,
              arrivalTimestamp: null,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "0000132",
                name: "Bahn-2000-Strecke",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.196371,
                  y: 7.689367,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:26:00+0200",
              arrivalTimestamp: 1651425960,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "9",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8500218",
            name: "Olten",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.351936,
              y: 7.907707,
            },
            distance: null,
          },
          arrival: "2022-05-01T18:48:00+0200",
          arrivalTimestamp: 1651423680,
          departure: "2022-05-01T18:58:00+0200",
          departureTimestamp: 1651424280,
          delay: null,
          platform: "8",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8500218",
            name: "Olten",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.351936,
              y: 7.907707,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
          arrival: "2022-05-01T19:26:00+0200",
          arrivalTimestamp: 1651425960,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "9",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
        },
      },
      {
        journey: {
          name: "000730",
          category: "IC",
          subcategory: null,
          categoryCode: null,
          number: "1",
          operator: "SBB",
          to: "Genève-Aéroport",
          passList: [
            {
              station: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:26:00+0200",
              arrivalTimestamp: 1651425960,
              departure: "2022-05-01T19:34:00+0200",
              departureTimestamp: 1651426440,
              delay: null,
              platform: "3",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8507000",
                name: "Bern",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.948832,
                  y: 7.439136,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504100",
                name: "Fribourg/Freiburg",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.803151,
                  y: 7.151052,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:55:00+0200",
              arrivalTimestamp: 1651427700,
              departure: "2022-05-01T19:56:00+0200",
              departureTimestamp: 1651427760,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504100",
                name: "Fribourg/Freiburg",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.803151,
                  y: 7.151052,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501120",
                name: "Lausanne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.516795,
                  y: 6.629087,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:40:00+0200",
              arrivalTimestamp: 1651430400,
              departure: "2022-05-01T20:43:00+0200",
              departureTimestamp: 1651430580,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501120",
                name: "Lausanne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.516795,
                  y: 6.629087,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
              arrival: "2022-05-01T21:18:00+0200",
              arrivalTimestamp: 1651432680,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "3",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
          arrival: "2022-05-01T19:26:00+0200",
          arrivalTimestamp: 1651425960,
          departure: "2022-05-01T19:34:00+0200",
          departureTimestamp: 1651426440,
          delay: null,
          platform: "3",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8507000",
            name: "Bern",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.948832,
              y: 7.439136,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
          arrival: "2022-05-01T21:18:00+0200",
          arrivalTimestamp: 1651432680,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "3",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
        },
      },
    ],
  },
  {
    from: {
      station: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
      arrival: null,
      arrivalTimestamp: null,
      departure: "2022-05-01T19:03:00+0200",
      departureTimestamp: 1651424580,
      delay: null,
      platform: "14",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8500010",
        name: "Basel SBB",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 47.547412,
          y: 7.589577,
        },
        distance: null,
      },
    },
    to: {
      station: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
      arrival: "2022-05-01T22:20:00+0200",
      arrivalTimestamp: 1651436400,
      departure: null,
      departureTimestamp: null,
      delay: null,
      platform: "3",
      prognosis: {
        platform: null,
        arrival: null,
        departure: null,
        capacity1st: null,
        capacity2nd: null,
      },
      realtimeAvailability: null,
      location: {
        id: "8501008",
        name: "Genève",
        score: null,
        coordinate: {
          type: "WGS84",
          x: 46.210228,
          y: 6.142435,
        },
        distance: null,
      },
    },
    duration: "00d03:17:00",
    transfers: 2,
    service: null,
    products: ["IC 51", "IC 5", "RE"],
    capacity1st: null,
    capacity2nd: null,
    sections: [
      {
        journey: {
          name: "001634",
          category: "IC",
          subcategory: null,
          categoryCode: null,
          number: "51",
          operator: "SBB",
          to: "Biel/Bienne",
          passList: [
            {
              station: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
              arrival: null,
              arrivalTimestamp: null,
              departure: "2022-05-01T19:03:00+0200",
              departureTimestamp: 1651424580,
              delay: null,
              platform: "14",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500010",
                name: "Basel SBB",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.547412,
                  y: 7.589577,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500113",
                name: "Laufen",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.419347,
                  y: 7.502642,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:20:00+0200",
              arrivalTimestamp: 1651425600,
              departure: "2022-05-01T19:21:00+0200",
              departureTimestamp: 1651425660,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500113",
                name: "Laufen",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.419347,
                  y: 7.502642,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500109",
                name: "Delémont",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.36201,
                  y: 7.35008,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:37:00+0200",
              arrivalTimestamp: 1651426620,
              departure: "2022-05-01T19:42:00+0200",
              departureTimestamp: 1651426920,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500109",
                name: "Delémont",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.36201,
                  y: 7.35008,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500105",
                name: "Moutier",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.280676,
                  y: 7.38105,
                },
                distance: null,
              },
              arrival: "2022-05-01T19:51:00+0200",
              arrivalTimestamp: 1651427460,
              departure: "2022-05-01T19:52:00+0200",
              departureTimestamp: 1651427520,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500105",
                name: "Moutier",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.280676,
                  y: 7.38105,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8500159",
                name: "Grenchen Nord",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.191696,
                  y: 7.38963,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:00:00+0200",
              arrivalTimestamp: 1651428000,
              departure: "2022-05-01T20:01:00+0200",
              departureTimestamp: 1651428060,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8500159",
                name: "Grenchen Nord",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.191696,
                  y: 7.38963,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:10:00+0200",
              arrivalTimestamp: 1651428600,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "4",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
          arrival: null,
          arrivalTimestamp: null,
          departure: "2022-05-01T19:03:00+0200",
          departureTimestamp: 1651424580,
          delay: null,
          platform: "14",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8500010",
            name: "Basel SBB",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.547412,
              y: 7.589577,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
          arrival: "2022-05-01T20:10:00+0200",
          arrivalTimestamp: 1651428600,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "4",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
        },
      },
      {
        journey: {
          name: "000534",
          category: "IC",
          subcategory: null,
          categoryCode: null,
          number: "5",
          operator: "SBB",
          to: "Morges",
          passList: [
            {
              station: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:10:00+0200",
              arrivalTimestamp: 1651428600,
              departure: "2022-05-01T20:16:00+0200",
              departureTimestamp: 1651428960,
              delay: null,
              platform: "5",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504300",
                name: "Biel/Bienne",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 47.132902,
                  y: 7.242918,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504221",
                name: "Neuchâtel",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.996727,
                  y: 6.935713,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:32:00+0200",
              arrivalTimestamp: 1651429920,
              departure: "2022-05-01T20:34:00+0200",
              departureTimestamp: 1651430040,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504221",
                name: "Neuchâtel",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.996727,
                  y: 6.935713,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8504200",
                name: "Yverdon-les-Bains",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.78155,
                  y: 6.640943,
                },
                distance: null,
              },
              arrival: "2022-05-01T20:52:00+0200",
              arrivalTimestamp: 1651431120,
              departure: "2022-05-01T20:54:00+0200",
              departureTimestamp: 1651431240,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8504200",
                name: "Yverdon-les-Bains",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.78155,
                  y: 6.640943,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501037",
                name: "Morges",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.511111,
                  y: 6.493971,
                },
                distance: null,
              },
              arrival: "2022-05-01T21:16:00+0200",
              arrivalTimestamp: 1651432560,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "3",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501037",
                name: "Morges",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.511111,
                  y: 6.493971,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
          arrival: "2022-05-01T20:10:00+0200",
          arrivalTimestamp: 1651428600,
          departure: "2022-05-01T20:16:00+0200",
          departureTimestamp: 1651428960,
          delay: null,
          platform: "5",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8504300",
            name: "Biel/Bienne",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 47.132902,
              y: 7.242918,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8501037",
            name: "Morges",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.511111,
              y: 6.493971,
            },
            distance: null,
          },
          arrival: "2022-05-01T21:16:00+0200",
          arrivalTimestamp: 1651432560,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "3",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8501037",
            name: "Morges",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.511111,
              y: 6.493971,
            },
            distance: null,
          },
        },
      },
      {
        journey: {
          name: "018436",
          category: "RE",
          subcategory: null,
          categoryCode: null,
          number: "018436",
          operator: "SBB",
          to: "Genève-Aéroport",
          passList: [
            {
              station: {
                id: "8501037",
                name: "Morges",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.511111,
                  y: 6.493971,
                },
                distance: null,
              },
              arrival: "2022-05-01T21:16:00+0200",
              arrivalTimestamp: 1651432560,
              departure: "2022-05-01T21:35:00+0200",
              departureTimestamp: 1651433700,
              delay: null,
              platform: "2",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501037",
                name: "Morges",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.511111,
                  y: 6.493971,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501035",
                name: "Allaman",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.475769,
                  y: 6.399696,
                },
                distance: null,
              },
              arrival: "2022-05-01T21:40:00+0200",
              arrivalTimestamp: 1651434000,
              departure: "2022-05-01T21:42:00+0200",
              departureTimestamp: 1651434120,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501035",
                name: "Allaman",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.475769,
                  y: 6.399696,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501033",
                name: "Rolle",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.462757,
                  y: 6.3364,
                },
                distance: null,
              },
              arrival: "2022-05-01T21:53:00+0200",
              arrivalTimestamp: 1651434780,
              departure: "2022-05-01T21:53:00+0200",
              departureTimestamp: 1651434780,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501033",
                name: "Rolle",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.462757,
                  y: 6.3364,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501031",
                name: "Gland",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.419998,
                  y: 6.269128,
                },
                distance: null,
              },
              arrival: "2022-05-01T21:58:00+0200",
              arrivalTimestamp: 1651435080,
              departure: "2022-05-01T21:59:00+0200",
              departureTimestamp: 1651435140,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501031",
                name: "Gland",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.419998,
                  y: 6.269128,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501030",
                name: "Nyon",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.38443,
                  y: 6.235963,
                },
                distance: null,
              },
              arrival: "2022-05-01T22:02:00+0200",
              arrivalTimestamp: 1651435320,
              departure: "2022-05-01T22:04:00+0200",
              departureTimestamp: 1651435440,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501030",
                name: "Nyon",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.38443,
                  y: 6.235963,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501023",
                name: "Coppet",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.317405,
                  y: 6.187819,
                },
                distance: null,
              },
              arrival: "2022-05-01T22:09:00+0200",
              arrivalTimestamp: 1651435740,
              departure: "2022-05-01T22:11:00+0200",
              departureTimestamp: 1651435860,
              delay: null,
              platform: null,
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501023",
                name: "Coppet",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.317405,
                  y: 6.187819,
                },
                distance: null,
              },
            },
            {
              station: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
              arrival: "2022-05-01T22:20:00+0200",
              arrivalTimestamp: 1651436400,
              departure: null,
              departureTimestamp: null,
              delay: null,
              platform: "3",
              prognosis: {
                platform: null,
                arrival: null,
                departure: null,
                capacity1st: null,
                capacity2nd: null,
              },
              realtimeAvailability: null,
              location: {
                id: "8501008",
                name: "Genève",
                score: null,
                coordinate: {
                  type: "WGS84",
                  x: 46.210228,
                  y: 6.142435,
                },
                distance: null,
              },
            },
          ],
          capacity1st: null,
          capacity2nd: null,
        },
        walk: null,
        departure: {
          station: {
            id: "8501037",
            name: "Morges",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.511111,
              y: 6.493971,
            },
            distance: null,
          },
          arrival: "2022-05-01T21:16:00+0200",
          arrivalTimestamp: 1651432560,
          departure: "2022-05-01T21:35:00+0200",
          departureTimestamp: 1651433700,
          delay: null,
          platform: "2",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8501037",
            name: "Morges",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.511111,
              y: 6.493971,
            },
            distance: null,
          },
        },
        arrival: {
          station: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
          arrival: "2022-05-01T22:20:00+0200",
          arrivalTimestamp: 1651436400,
          departure: null,
          departureTimestamp: null,
          delay: null,
          platform: "3",
          prognosis: {
            platform: null,
            arrival: null,
            departure: null,
            capacity1st: null,
            capacity2nd: null,
          },
          realtimeAvailability: null,
          location: {
            id: "8501008",
            name: "Genève",
            score: null,
            coordinate: {
              type: "WGS84",
              x: 46.210228,
              y: 6.142435,
            },
            distance: null,
          },
        },
      },
    ],
  },
] as unknown as Connection[];
