import { Container } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import TimetableSearch from "../src/components/TimetableSearch";
import { TimetableSearchProvider } from "../src/components/TimetableSearchProvider";

const Home: NextPage = () => {
  return (
    <>
      {/* TODO - FIX HEAD */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <TimetableSearchProvider>
            <TimetableSearch />
          </TimetableSearchProvider>
        </Container>
      </main>
    </>
  );
};

export default Home;
